import Link from 'next/link'
import { ArrowLeft, FileText, Scale, ShieldAlert, Zap, HelpCircle, Mail } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden grain">
      {/* Ambient glow */}
      <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] pointer-events-none -z-10" />
      
      {/* Header */}
      <header className="border-b border-border/50 bg-background/80 backdrop-blur-xl sticky top-0 z-50">
        <nav className="container flex items-center justify-between py-4">
          <Link href="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors group">
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="text-sm font-bold uppercase tracking-widest font-heading">Back</span>
          </Link>
          <Link href="/" className="flex items-center gap-3">
            <img src="/sparkyn_logo.jpg" alt="Sparkyn Logo" className="w-8 h-8 rounded-lg" />
            <span className="text-lg font-extrabold font-heading tracking-tight text-white">Sparkyn</span>
          </Link>
          <div className="w-20" /> {/* Spacer for balance */}
        </nav>
      </header>

      <main className="container max-w-4xl py-20 px-6">
        {/* Title Section */}
        <div className="space-y-6 mb-16 text-center">
          <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center border border-primary/20 mx-auto">
            <FileText className="text-primary w-8 h-8" />
          </div>
          <h1 className="text-5xl font-black font-heading tracking-tighter text-white">Terms of Service</h1>
          <div className="flex items-center justify-center gap-2 text-muted-foreground">
            <span className="w-2 h-2 rounded-full bg-primary/40" />
            <p className="text-xs font-bold uppercase tracking-[0.2em]">Effective March 19, 2026</p>
          </div>
        </div>

        {/* Content Section */}
        <div className="space-y-12 text-muted-foreground leading-relaxed">
          <section className="space-y-6 bg-card/30 p-8 rounded-[2rem] border border-border/50">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary">
                <Scale className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">1. Acceptance</h2>
            </div>
            <p className="text-lg">
              By accessing and using Sparkyn, you agree to be bound by these Terms of Service. Sparkyn provides automated social media marketing tools powered by proprietary AI engines and Google Gemini.
            </p>
          </section>

          <section className="space-y-6 p-8">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary">
                <ShieldAlert className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">2. User Responsibility</h2>
            </div>
            <p className="text-lg">
              As a content creator or business owner, you are ultimately responsible for the content generated by the AI and published through your connected accounts. While Sparkyn automates the process, you must ensure all content complies with the community guidelines of Meta, TikTok, and YouTube.
            </p>
          </section>

          <section className="space-y-6 bg-card/30 p-8 rounded-[2rem] border border-border/50">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary">
                <Zap className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">3. Service Performance</h2>
            </div>
            <p className="text-lg">
              Sparkyn uses third-party AI models. We do not guarantee specific engagement metrics, viral success, or absolute accuracy of AI-generated content. Automation is subject to the technical availability of social media platform APIs.
            </p>
          </section>

          <section className="space-y-6 p-8">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary">
                <HelpCircle className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">4. Usage & Spam</h2>
            </div>
            <p className="text-lg">
              Spamming, harassment, or the automation of illegal content is strictly prohibited. Sparkyn reserves the right to terminate accounts that use the "Creator Engine" to violate the integrity of social media platforms or harass other users.
            </p>
          </section>

          <section className="text-center pt-10 pb-20 border-t border-border/50">
            <h2 className="text-xl font-bold font-heading text-white mb-4">Terms Clarification</h2>
            <p className="text-sm mb-8">Need more details on our service agreement?</p>
            <a href="mailto:legal@sparkyn.ai" className="btn btn-outline gap-2 py-4 px-8 border-primary/20 hover:border-primary text-primary font-bold">
              <Mail className="w-4 h-4" /> legal@sparkyn.ai
            </a>
          </section>
        </div>
      </main>

      {/* Footer link */}
      <footer className="py-12 border-t border-border/50 bg-card/20">
        <div className="container text-center">
          <Link href="/privacy" className="text-xs font-bold uppercase tracking-widest text-muted-foreground hover:text-primary transition-colors">
            View Privacy Policy
          </Link>
        </div>
      </footer>
    </div>
  )
}
