import Link from 'next/link'
import { Sparkles, FileText, Scale, ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="container flex items-center justify-between py-6">
        <Link href="/" className="flex items-center gap-2 group">
          <ArrowLeft className="w-4 h-4 text-muted-foreground group-hover:-translate-x-1 transition-transform" />
          <span className="text-sm font-medium">Back to Home</span>
        </Link>
        <div className="flex items-center gap-2">
          <Sparkles className="text-primary w-6 h-6" />
          <span className="text-xl font-bold tracking-tighter">Sparkyn</span>
        </div>
      </nav>

      <main className="container max-w-3xl py-12 space-y-12 pb-32">
        <div className="space-y-4">
          <div className="p-3 bg-primary/10 rounded-2xl w-fit">
            <FileText className="text-primary w-6 h-6" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
          <p className="text-muted-foreground text-sm font-medium">Last updated: March 19, 2026</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2 border-b border-border pb-2">
              <Scale className="w-5 h-5 text-primary" /> 1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using Sparkyn, you agree to be bound by these Terms of Service. Sparkyn provides AI-driven social media automation tools for businesses.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-foreground border-b border-border pb-2">
              2. User Responsibility
            </h2>
            <p>
              Users are responsible for the content generated by the AI and published through their accounts. You must comply with the community guidelines of all connected platforms (Meta, TikTok, YouTube).
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-foreground border-b border-border pb-2">
              3. Service Limitations
            </h2>
            <p>
              Sparkyn uses third-party AI models. We do not guarantee the performance of ANY post or the absolute accuracy of AI-generated content. Posting is subject to the up-time and API limits of social media providers.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-foreground border-b border-border pb-2">
              4. Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate our terms or misuse the automation features to spam or harass other users on social media platforms.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
