import Link from 'next/link'
import { ArrowLeft, FileText, Scale, ShieldAlert, Zap, HelpCircle, Mail, ChevronRight } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient relative overflow-hidden grain">
      {/* Ambient glow - Amber */}
      <div className="absolute top-[-10%] left-[50%] -translate-x-1/2 w-[600px] h-[600px] bg-primary/10 rounded-full blur-[120px] pointer-events-none -z-10" />
      {/* Ambient glow - Success/Emerald */}
      <div className="absolute bottom-[-10%] right-0 w-[400px] h-[400px] bg-success/5 rounded-full blur-[100px] pointer-events-none -z-10" />
      
      {/* Header */}
      <header className="border-b border-white/5 bg-background/80 backdrop-blur-xl sticky top-0 z-50">
        <nav className="container max-w-7xl flex items-center justify-between py-4">
          <Link href="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-all group">
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="text-xs font-bold uppercase tracking-widest font-heading">Home</span>
          </Link>
          <Link href="/" className="flex items-center gap-2 group">
            <img src="/sparkyn_logo.jpg" alt="Sparkyn Logo" className="w-6 h-6 rounded-sm transition-transform group-hover:scale-110" />
            <span className="text-xl font-black font-heading tracking-tighter text-white">Sparkyn</span>
          </Link>
          <div className="w-16" /> {/* Spacer for balance */}
        </nav>
      </header>

      <main className="container max-w-3xl py-16 px-6 relative z-10">
        {/* Title Section */}
        <div className="space-y-6 mb-20 text-center animate-fade-in-up">
          <div className="w-14 h-14 bg-primary/10 rounded-2xl flex items-center justify-center border border-primary/20 mx-auto glow-amber">
            <FileText className="text-primary w-7 h-7" />
          </div>
          <h1 className="text-4xl md:text-6xl font-black font-heading tracking-tighter text-white">
            Terms of <span className="glow-text">Service</span>
          </h1>
          <div className="flex items-center justify-center gap-2 py-1 px-4 bg-white/5 rounded-full w-fit mx-auto border border-white/10">
            <span className="w-1.5 h-1.5 rounded-full bg-primary pulse-dot" />
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Effective March 19, 2026</p>
          </div>
        </div>

        {/* Content Section */}
        <div className="space-y-12">
          <section className="space-y-6 group p-8 rounded-3xl bg-white/[0.03] border border-white/5 hover:border-white/10 transition-all">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary transition-colors group-hover:bg-primary/20">
                <Scale className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">1. Acceptance</h2>
            </div>
            <p className="text-lg leading-relaxed text-muted-foreground">
              By accessing and using Sparkyn, you agree to be bound by these Terms of Service. Sparkyn provides automated social media marketing tools powered by proprietary AI engines and Google Gemini.
            </p>
          </section>

          <section className="space-y-6 group">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-success/10 rounded-xl flex items-center justify-center border border-success/20 text-success transition-colors group-hover:bg-success/20">
                <ShieldAlert className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">2. User Responsibility</h2>
            </div>
            <p className="text-lg leading-relaxed text-muted-foreground">
              As a content creator or business owner, you are ultimately responsible for the content generated by the AI and published through your connected accounts. While Sparkyn automates the process, you must ensure all content complies with the community guidelines of Meta, TikTok, and YouTube.
            </p>
          </section>

          <section className="space-y-6 group p-8 rounded-3xl bg-white/[0.03] border border-white/5 hover:border-white/10 transition-all">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 text-primary">
                <Zap className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">3. Service Performance</h2>
            </div>
            <p className="text-lg leading-relaxed text-muted-foreground">
              Sparkyn uses third-party AI models. We do not guarantee specific engagement metrics, viral success, or absolute accuracy of AI-generated content. Automation is subject to the technical availability of social media platform APIs.
            </p>
          </section>

          <section className="space-y-6 group">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-success/10 rounded-xl flex items-center justify-center border border-success/20 text-success">
                <HelpCircle className="w-5 h-5" />
              </div>
              <h2 className="text-2xl font-bold font-heading text-white tracking-tight">4. Usage & Spam</h2>
            </div>
            <p className="text-lg leading-relaxed text-muted-foreground">
              Spamming, harassment, or the automation of illegal content is strictly prohibited. Sparkyn reserves the right to terminate accounts that use the "Creator Engine" to violate the integrity of social media platforms or harass other users.
            </p>
          </section>

          <section className="text-center pt-20 pb-20 border-t border-white/10">
            <h2 className="text-xl font-bold font-heading text-white mb-4">Terms Clarification</h2>
            <p className="text-sm text-muted-foreground mb-10">Need more details on our service agreement?</p>
            <a href="mailto:legal@sparkyn.ai" className="btn btn-primary gap-2 py-4 px-10 rounded-2xl glow-amber font-bold">
              <Mail className="w-4 h-4" /> legal@sparkyn.ai
            </a>
          </section>
        </div>
      </main>

      {/* Footer link */}
      <footer className="py-12 border-t border-white/5 bg-white/[0.02]">
        <div className="container text-center space-y-4">
          <Link href="/privacy" className="text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground hover:text-primary transition-colors">
            View Privacy Policy
          </Link>
          <p className="text-[10px] text-white/20">© 2026 Sparkyn Automation. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
